-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgg8PDlOjTPWF1YAqa
yAJ2GuANfMiE7rCmzS7J99CLozGgCgYIKoZIzj0DAQehRANCAASgAjtctn3gG3pv
I/nTlimDh/G+NKUAVtS7pmNJoHExJ0HHOMqcH22V5+MiPRnzTT9/25KQWIPOY9az
K51rQMBD
-----END PRIVATE KEY-----